import type { Event, Club } from './types';

export const events: Event[] = [
  {
    id: '1',
    title: 'Nexus Conference 2024',
    description: 'An annual tech conference bringing together the brightest minds in AI, blockchain, and quantum computing. Features keynote speakers from major tech companies.',
    date: '2024-10-26',
    time: '09:00 AM',
    venue: 'Grand Auditorium, Tech Park',
    category: 'Technology',
    image: 'event-1',
  },
  {
    id: '2',
    title: 'Campus Beats Music Festival',
    description: 'A two-day music festival featuring student bands, local artists, and a surprise headliner. Food trucks, art installations, and more!',
    date: '2024-09-15',
    time: '03:00 PM',
    venue: 'University Great Lawn',
    category: 'Music',
    image: 'event-2',
  },
  {
    id: '3',
    title: 'Visions: Annual Art Exhibit',
    description: 'Explore the creative talents of our fine arts students. The exhibition showcases paintings, sculptures, and digital media.',
    date: '2024-11-05',
    time: '06:00 PM',
    venue: 'Harrison Art Gallery',
    category: 'Arts',
    image: 'event-3',
  },
  {
    id: '4',
    title: 'InnovateX Hackathon',
    description: 'A 36-hour coding marathon where teams build innovative solutions to real-world problems. Prizes, mentorship, and lots of coffee.',
    date: '2024-11-22',
    time: '07:00 PM',
    venue: 'Engineering Building, Labs 1-5',
    category: 'Technology',
    image: 'event-4',
  },
  {
    id: '5',
    title: 'Future Forward: Career Fair',
    description: 'Connect with top employers from various industries. Bring your resume and dress to impress. Open to all majors.',
    date: '2024-10-10',
    time: '10:00 AM',
    venue: 'Student Union Ballroom',
    category: 'Career',
    image: 'event-5',
  },
  {
    id: '6',
    title: 'Graduation Gala',
    description: 'A night of celebration for the graduating class. Dinner, dancing, and a final farewell to your university years.',
    date: '2024-12-15',
    time: '07:00 PM',
    venue: 'Crystal Ballroom Downtown',
    category: 'Social',
    image: 'event-6',
  },
  {
    id: '7',
    title: 'Festival of Cultures',
    description: 'Experience the world in one day. A celebration of the diverse cultures on campus with food, music, and dance from around the globe.',
    date: '2024-10-01',
    time: '12:00 PM',
    venue: 'Central Quad',
    category: 'Cultural',
    image: 'event-7',
  },
];

export const clubs: Club[] = [
  {
    id: '1',
    name: 'CodeCrafters Society',
    description: 'A community for students passionate about coding. We host weekly workshops, coding competitions, and project collaborations.',
    category: 'Academic',
    image: 'club-1',
    isVerified: true,
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Debate Union',
    description: 'Hone your public speaking and argumentation skills. We participate in regional and national debate tournaments.',
    category: 'Academic',
    image: 'club-2',
    isVerified: true,
    isFeatured: false,
  },
  {
    id: '3',
    name: 'Astronomy Club "Stargazers"',
    description: 'Explore the cosmos with us. We organize stargazing nights, talks by astronomers, and trips to observatories.',
    category: 'Hobbies',
    image: 'club-3',
    isVerified: false,
    isFeatured: true,
  },
  {
    id: '4',
    name: 'The Art Collective',
    description: 'A space for all artists, from painters to digital illustrators. Join us for creative sessions and gallery visits.',
    category: 'Arts',
    image: 'club-4',
    isVerified: true,
    isFeatured: true,
  },
  {
    id: '5',
    name: 'Chess Masters',
    description: 'For lovers of the classic strategy game. All skill levels are welcome, from grandmasters in training to absolute beginners.',
    category: 'Hobbies',
    image: 'club-5',
    isVerified: false,
    isFeatured: false,
  },
  {
    id: '6',
    name: 'Outdoor Adventure Club',
    description: 'If you love hiking, camping, and the great outdoors, this is the club for you. We organize regular trips and activities.',
    category: 'Sports',
    image: 'club-6',
    isVerified: true,
    isFeatured: true,
  },
];
